quick-perf/quickperf

core/src/main/java/org/quickperf/WorkingFolder.java

Tests were failing with the following stack 
```
-------------------------------------------------------
T E S T S
-------------------------------------------------------
Running org.quickperf.junit4.QuickPerfJUnitRunnerTest
Unable to run test in a new JMV: Exception in thread "main" java.lang.IllegalStateException: java.io.FileNotFoundException: /tmpQuickPerf-1470442387/junitFailures.ser (Aucun fichier ou dossier de ce type)
at org.quickperf.repository.ObjectOutputStreamBuilder.buildFileOutputStream(ObjectOutputStreamBuilder.java:51)
at org.quickperf.repository.ObjectOutputStreamBuilder.build(ObjectOutputStreamBuilder.java:33)
at org.quickperf.repository.ObjectFileRepository.save(ObjectFileRepository.java:40)
at org.quickperf.junit4.JUnit4FailuresRepository.save(JUnit4FailuresRepository.j …
```

Tests were failing on 5.1.7-arch1-1-ARCH

---

jvm-annotations/src/main/java/org/quickperf/jvm/JvmVersion.java
jvm-annotations/src/main/java/org/quickperf/jvm/allocation/bytewatcher/ByteWatcherRecorder.java

The build was failing with OpenJDK11 and Ubuntu OS. The automatic tests related to allocation measurements failed. See the attached logs.
[quickperf-annotationtest-failure.log](https://github.com/quick-perf/quickperf/files/3483140/quickperf-annotationtest-failure.log)

Fix allocation offset

---

CONTRIBUTING.md

I just added a small tips to build quickperf locally against multiple openjdk (thanks to docker).
It allow anyone who has docker installed to check linux build with multiple openjdk but it could be more like testing against amazon corretto 11 for instance.

Added tips to build QuickPerf.

---

junit5/pom.xml

Use the RC version to avoid using snapshots
junit5-jupiter version 5.6.0-RC1 
junit5-platform version 1.6.0-RC1

chore: bump junit5 versions to RC1

---

README.md
pom.xml
sql/sql-annotations/src/main/java/org/quickperf/sql/SqlExecutions.java
sql/sql-annotations/src/main/java/org/quickperf/sql/annotation/ExpectMaxUpdatedColumn.java
sql/sql-annotations/src/main/java/org/quickperf/sql/config/library/SqlAnnotationsConfigs.java
sql/sql-annotations/src/main/java/org/quickperf/sql/config/library/SqlConfigLoader.java
sql/sql-annotations/src/main/java/org/quickperf/sql/select/columns/MaxSelectedColumnsPerMeasureExtractor.java
sql/sql-annotations/src/main/java/org/quickperf/sql/update/columns/MaxUpdatedColumnsPerMeasureExtractor.java
sql/sql-annotations/src/main/java/org/quickperf/sql/update/columns/MaxUpdatedColumnsPerfIssueVerifier.java
sql/sql-integration-test/src/test/java/ExpectMaxUpdatedColumnTest.java

Users might want to ensure that a method to not update more columns that required. By putting `@ExpectMaxUpdatedColumn(3)` quickperf wil assert that no more than 3 columns have been updated.
We want to count columns passed in the update SQL query. We will count the parameter setted in the set clause of the query. We suppose also that with are using `PreparedStatement` to execute this update. This is what hibernate do.
How to return `2` in this example `UPDATE book SET isbn = ?, title = ? WHERE id = ?`
To count updated columns, we cannot rely on `query.getParametersList().get(0)` because this list will contains all 3 parameters of the query.
Instead we can count the occurrences of the character `?` which represent a parameter. We must count those occurrences only on the substring `SET isbn …

Add annotation @ExpectMaxUpdatedColumn

---

junit4/junit4-jvm-test/src/test/java/org/quickperf/jvm/rss/JUnit4RssTests.java
junit5/junit5-jvm-test/src/test/java/org/quickperf/junit5/jvm/rss/JUnit5RssTests.java
jvm/jvm-annotations/src/main/java/org/quickperf/jvm/annotations/ExpectMaxRSS.java
jvm/jvm-annotations/src/main/java/org/quickperf/jvm/annotations/JvmAnnotationBuilder.java
jvm/jvm-annotations/src/main/java/org/quickperf/jvm/annotations/MeasureRSS.java
jvm/jvm-annotations/src/main/java/org/quickperf/jvm/config/library/JvmAnnotationsConfigs.java
jvm/jvm-annotations/src/main/java/org/quickperf/jvm/config/library/JvmConfigLoader.java
jvm/jvm-annotations/src/main/java/org/quickperf/jvm/rss/ExpectRssPerfVerifier.java
jvm/jvm-annotations/src/main/java/org/quickperf/jvm/rss/MeasureRssPerfVerifier.java
jvm/jvm-annotations/src/main/java/org/quickperf/jvm/rss/ProcessStatus.java
jvm/jvm-annotations/src/main/java/org/quickperf/jvm/rss/ProcessStatusRecorder.java

Fixes #21
This PR adds RSS annotations to measure the Resident Set Size of the process of the test methods.
This only works for Linux.
It adds the capability to gather process statistics so other annotations can take advantage of it.
It adds the capability from an anotation to skip the fork if needed.

Provides RSS annotations

---

README.md
core/src/main/java/org/quickperf/unit/NoUnit.java
pom.xml
sql/sql-annotations/src/main/java/org/quickperf/sql/SqlExecutions.java
sql/sql-annotations/src/main/java/org/quickperf/sql/annotation/ExpectUpdatedColumn.java
sql/sql-annotations/src/main/java/org/quickperf/sql/annotation/SqlAnnotationBuilder.java
sql/sql-annotations/src/main/java/org/quickperf/sql/config/library/SqlAnnotationsConfigs.java
sql/sql-annotations/src/main/java/org/quickperf/sql/config/library/SqlConfigLoader.java
sql/sql-annotations/src/main/java/org/quickperf/sql/update/columns/NumberOfUpdatedColumnsStatistics.java
sql/sql-annotations/src/main/java/org/quickperf/sql/update/columns/NumberOfUpdatedColumnsStatisticsMeasure.java
sql/sql-annotations/src/main/java/org/quickperf/sql/update/columns/UpdatedColumnsMeasureExtractor.java
sql/sql-annotations/src/main/java/org/quickperf/sql/update/columns/UpdatedColumnsPerfIssueVerifier.java
sql/sql-integration-test/src/test/java/ExpectUpdatedColumnTest.java

I have tried following the [instructions][1]. The main changes include:
- Added the @ExpectUpdatedColumn annotation
- Added  `UpdatedColumnsMeasureExtractor` and `UpdatedColumnsPerfIssueVerifier` classes in the package `org/quickperf/sql/update/columns`
- The updated columns count getting from the exisitng method.
- Added the unit test
[1]: here:https://github.com/quick-perf/doc/wiki/Create-an-annotation#steps-to-follow-to-add-a-sql-annotation-to-quickperf

Add @ExpectUpdatedColumn annotation

---

jvm/jvm-annotations/src/main/java/org/quickperf/jvm/allocation/MeasureHeapAllocationPerfVerifier.java
jvm/jvm-annotations/src/main/java/org/quickperf/jvm/annotations/JvmAnnotationBuilder.java
jvm/jvm-annotations/src/main/java/org/quickperf/jvm/annotations/MeasureHeapAllocation.java

Hello, 
I added the possibility to pass a format as an attribute to the MeasureHeapAllocation annotation. 
The format is used to format the amount of memory formatted as a String by QuickPerf. 
The default format correspond to the one used in the current version of QuickPerf, to the existing code continues to work as it did previously. 
Writing a test can be done in the following: 
@Test @MeasureHeapAllocation(format = "Memory consumed: %s\n")
public void array_list() {
// some critical stuff here!
}
The result would be: 
Memory consumed: 314.0 bytes
-- José

Work on measure heap allocation report

---

jvm/jvm-annotations/src/main/java/org/quickperf/jvm/allocation/AllocationUnit.java
jvm/jvm-annotations/src/main/java/org/quickperf/jvm/allocation/ByteAllocationMeasureFormatter.java
jvm/jvm-annotations/src/main/java/org/quickperf/jvm/allocation/MaxHeapAllocationPerfVerifier.java
jvm/jvm-annotations/src/main/java/org/quickperf/jvm/allocation/MeasureHeapAllocationPerfVerifier.java
jvm/jvm-annotations/src/main/java/org/quickperf/jvm/allocation/NoHeapAllocationPerfVerifier.java
jvm/jvm-annotations/src/main/java/org/quickperf/jvm/jmc/value/DisplayJvmProfilingValueVerifier.java
jvm/jvm-annotations/src/main/java/org/quickperf/jvm/jmc/value/ProfilingInfo.java
jvm/jvm-annotations/src/main/java/org/quickperf/jvm/jmc/value/allocationrate/AllocationRate.java
jvm/jvm-annotations/src/main/java/org/quickperf/jvm/jmc/value/allocationrate/AllocationRateFormatter.java
jvm/jvm-annotations/src/main/java/org/quickperf/jvm/jmc/value/allocationrate/AllocationRateRetriever.java
jvm/jvm-annotations/src/main/java/org/quickperf/jvm/rss/ExpectMaxRssPerfVerifier.java
jvm/jvm-annotations/src/test/java/org/quickperf/jvm/ByteAllocationMeasureFormatterTest.java
jvm/jvm-annotations/src/test/java/org/quickperf/jvm/jmc/value/AllocationRateTest.java
testng/testng-jvm-test/src/test/java/org/quickperf/testng/jvm/jmc/AllocationRateProfileJVMTest.java

* Initial Commit. Reformat, Rearrange, CheckStyle and Tests required.
* Added AllocationRate test classes
* Pretty formatting of Jvm Profiling output.
* Fix failing tests
* Minor test improvements
* Add licence headers
* Minor improvements
* Fix build issue and simplify exception management
* Simplify exception management
* Time stamp should have no reason to be negative
* Fix typo
* Fix compilation warning
* Separation of concerns and code simplification
* Extract methods
* Allocation duration has no reason to be negative
* Remove local variable
* Should return an empty string if allocation duration is zero
* Simplify code by removing not possible test cases
* Remove compilation warning
* Item collection has no reason to be null
* Thre is no reason to don't have JFR events
* With this …

 @ProfileJvm displays the allocation rate

---

jvm/jvm-annotations/src/main/java/org/quickperf/jvm/jmc/value/DisplayJvmProfilingValueVerifier.java

- a private method add ```getOldGcCount(IItemCollection jfrEvents)``` in ```DisplayJvmProfilingValueVerifier``` class
- display Old: (number of collections) below Longest GC pause
```
-----------------------------------------------------------------------------
ALLOCATION (estimations)   |   GARBAGE COLLECTION           |  THROWABLE
Total       : 58.1 MiB     |   Total pause: 117.111 ms      |  Exception: 0
Inside TLAB : 46.7 MiB     |   Longest GC pause: 81.672 ms  |  Error: 0
Outside TLAB: 11.4 MiB     |   Old: 0                       |  Throwable: 0
-----------------------------------------------------------------------------
COMPILATION                |   CODE CACHE
Number: 0                  |   The number of full code cache events: 0
Longest: 0                 | …
```

Make @profile jvm display the old gc count #70

---

jvm/jvm-annotations/src/main/java/org/quickperf/jvm/jmc/value/DisplayJvmProfilingValueVerifier.java

```
------------------------------------------------------------------------------
ALLOCATION (estimations)     |   GARBAGE COLLECTION           |  THROWABLE
Total       : 58.1 MiB       |   Total pause: 115.252 ms      |  Exception: 0
Inside TLAB : 46.7 MiB       |   Longest GC pause: 71.420 ms  |  Error: 0
Outside TLAB: 11.4 MiB       |   Old: 0                       |  Throwable: 0
Allocation rate: 272.8 MiB/s |   Young: 2                     |
------------------------------------------------------------------------------
COMPILATION                  |   CODE CACHE
Number: 0                    |   The number of full code cache events: 0
Longest: 0                   |   
------------------------------------------------------------------------------
```

make @Profile JVM display young gc collections

---

core/src/main/java/org/quickperf/SystemProperties.java
jvm/jfr-annotations/src/main/java/org/quickperf/jvm/jmc/value/DisplayJvmProfilingValueVerifier.java
sql/sql-annotations/src/main/java/org/quickperf/sql/SqlExecutions.java
sql/sql-annotations/src/main/java/org/quickperf/sql/delete/MaxOfDeletesPerfIssueVerifier.java
sql/sql-annotations/src/main/java/org/quickperf/sql/insert/MaxOfInsertsPerfIssueVerifier.java
sql/sql-annotations/src/main/java/org/quickperf/sql/select/HasSameSelectTypesWithDiffParamValuesVerifier.java
sql/sql-annotations/src/main/java/org/quickperf/sql/select/MaxOfSelectsPerfIssueVerifier.java
sql/sql-annotations/src/main/java/org/quickperf/sql/select/SelectNumberPerfIssueVerifier.java
sql/sql-annotations/src/main/java/org/quickperf/sql/update/MaxOfUpdatesPerfIssueVerifier.java

See issue #84 for feature's background:
This feature aims to reduce verbosity of some of QuickPerf feedbacks. Configurable verbosity has been added for the following annotations:
- @[ProfileJvm](https://github.com/quick-perf/doc/wiki/JVM-annotations#profilejvm) annotation with JVM boolean option `-DlimitQuickPerfJvmInfoOnConsole`.
The only information displayed on the console will be the location of the file generated by the Java Flight Recorder when JVM option set to true.
- [SQL annotations](https://github.com/quick-perf/doc/wiki/SQL-annotations) involving JDBC roundtrips (@ExpectMaxUpdate, @ExpectMaxDelete, @ExpectMaxInsert, @ExpectMaxSelect and @ExpectSelect) and @DisableSameSelectTypesWithDifferentParamValues. 
Framework, JDBC batching suggestions and details of the executed queries …

add configurable verbosity

---

junit5/junit5-extension/src/main/java/org/quickperf/junit5/QuickPerfTestExtension.java
junit5/junit5-sql-test/src/test/java/org/quickperf/sql/QuickPerfJUnit5SqlDynamicTest.java

It didn't support JVM annotations yet as we cannot fork the VM due to https://github.com/junit-team/junit5/issues/2399
PerformanceReport are done per dynamic test but annotation declaration are per test factory method so the same annotation will be used by all dynamic test provided by a test factory method. This needs to be taken into account when creating multiple dynamic tests on a single test factory method.
When merged, I'll provide an example application.
Documentation will also need to be updated.

Support dynamic tests

---

junit4/junit4-12-jvm-test/pom.xml
junit4/junit4-13-1-jvm-test/pom.xml
junit4/junit4-13-jvm-test/pom.xml
junit4/junit4-5-jvm-test/pom.xml
junit4/junit4-sql-test/pom.xml
junit4/pom.xml
junit5/junit5-jvm-test/pom.xml
junit5/junit5-sql-test/pom.xml
junit5/junit5-test-util/pom.xml
junit5/pom.xml
pom.xml
spring/junit4-spring-base-tests/pom.xml
spring/junit4-spring-boot-test/pom.xml
spring/pom.xml
sql/pom.xml
sql/sql-hibernate-test-util/pom.xml
sql/sql-memory-test-util/pom.xml
sql/sql-memory-test/pom.xml
testng/pom.xml
testng/testng-jvm-test/pom.xml
testng/testng-sql-test/pom.xml
testng/testng-test-util/pom.xml

this will avoid build failures of release because pom version has not been updated and is still at 1.0-SNAPSHOT, while still avoiding deploying artifacts

replace release profile with maven.deploy.skip #126

---

core/src/main/java/org/quickperf/TestExecutionContext.java
junit5/junit5-extension/src/main/java/org/quickperf/junit5/QuickPerfTestExtension.java
junit5/junit5-jvm-test/src/test/java/org/quickperf/junit5/jvm/testtemplate/AllocationJUnit5TestTemplateTest.java
junit5/junit5-sql-test/src/test/java/org/quickperf/sql/QuickPerfJUnit5SqlTestTemplateTest.java

Support JUnit 5 test template: https://junit.org/junit5/docs/current/user-guide/#writing-tests-test-templates
Tests has been integrated with `@RepeatedTest` that is a build-in test template extension for repeated test.
Parameterized test should also works.
As for dynamic test, the annotation will apply for each test invocation derived from the test template method.

Support JUnit5 test template

---

spring/junit4-spring-boot-test/src/main/java/org/quickperf/spring/springboottest/jpa/entity/Player.java
spring/junit4-spring-boot-test/src/test/java/org/quickperf/spring/springboottest/QuickPerfSpringRunnerBeforeNewJvmTest.java
spring/junit4-spring-boot-test/src/test/java/org/quickperf/spring/springboottest/QuickPerfSpringRunnerBeforeTest.java
spring/junit4-spring3/src/main/java/org/quickperf/spring/junit4/SpringRunnerWithQuickPerfFeatures.java
spring/junit4-spring4/src/main/java/org/quickperf/spring/junit4/SpringRunnerWithQuickPerfFeatures.java
spring/junit4-spring5/src/main/java/org/quickperf/spring/junit4/SpringRunnerWithQuickPerfFeatures.java

```java
@RunWith(QuickPerfSpringRunner.class)
@Import(QuickPerfSqlConfig.class)
@DataJpaTest()
public class QuickPerfSpringRunnerBeforeTest {
@Autowired
private TestEntityManager testEntityManager;
@Before
public void before() {
Player player = new Player();
testEntityManager.persist(player);
}
@Test
public void test() {
}
}
```
Exception: `java.lang.IllegalStateException: No transactional EntityManager found`

QuickPerfSpringRunner did not call the Spring TestExecutionListener instances before the test method execution

---

spring/junit4-spring-boot-test/src/test/java/org/quickperf/spring/springboottest/QuickPerfSpringRunnerBeforeAfterNewJvmTest.java
spring/junit4-spring-boot-test/src/test/java/org/quickperf/spring/springboottest/QuickPerfSpringRunnerBeforeAfterTest.java
spring/junit4-spring3/src/main/java/org/quickperf/spring/junit4/SpringRunnerWithQuickPerfFeatures.java
spring/junit4-spring4/src/main/java/org/quickperf/spring/junit4/SpringRunnerWithQuickPerfFeatures.java
spring/junit4-spring5/src/main/java/org/quickperf/spring/junit4/SpringRunnerWithQuickPerfFeatures.java

```java
@RunWith(QuickPerfSpringRunner.class)
@Import(QuickPerfSqlConfig.class)
@DataJpaTest()
public class QuickPerfSpringRunnerAfterTest {
@Autowired
private TestEntityManager testEntityManager;
@Test
public void should_find_all_players() {
}
@After
public void after() {
Player player = new Player();
testEntityManager.persist(player);
}
}
```
Exception:  `No transactional EntityManager found`

QuickPerfSpringRunner did not call the Spring TestExecutionListener instances after the test method execution

---

jvm/jvm-annotations/src/main/java/org/quickperf/jvm/gc/GC.java

fix option name mistake in SHENANDOAH entry.

Issue-159 : update GC enum to use Shenandoah

---

jvm/jvm-annotations/src/main/java/org/quickperf/jvm/JvmOptionConverter.java

remove `jvmOptions != null` to simplify (`jvmOptions` can not be null at this point)

issue-160 : remove 'jvmOptions != null'

---

spring/junit4-spring3/src/main/java/org/quickperf/spring/junit4/QuickPerfSpringRunner.java
spring/junit4-spring4/src/main/java/org/quickperf/spring/junit4/QuickPerfSpringRunner.java
spring/junit4-spring5/src/main/java/org/quickperf/spring/junit4/QuickPerfSpringRunner.java

This issue happened during the development of the folowing PR on the update of file headers (license).
The stack:
```
java.lang.NullPointerException
at org.quickperf.spring.junit4.QuickPerfSpringRunner.setScheduler(QuickPerfSpringRunner.java:558)
at org.apache.maven.surefire.junitcore.pc.ParallelComputerBuilder$PC.setSchedulers(ParallelComputerBuilder.java:608)
at org.apache.maven.surefire.junitcore.pc.ParallelComputerBuilder$PC.setSchedulers(ParallelComputerBuilder.java:568)
at org.apache.maven.surefire.junitcore.pc.ParallelComputerBuilder$PC.getSuite(ParallelComputerBuilder.java:367)
at org.junit.runner.Request.classes(Request.java:75)
at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:126)
at …
```

Fix NPE in QuickPerfSpringRunner (JUnit 4) with Surefire

---

.github/workflows/CI.yml
junit4/junit4-12-jvm-test/pom.xml
junit5/junit5-jvm-test/pom.xml
junit5/junit5-test-util/pom.xml
jvm/jfr-annotations/pom.xml
jvm/jfr-annotations/src/main/java/org/quickperf/jvm/jmcrule/JmcRuleCountMeasureExtractor.java
pom.xml
spring/junit4-spring-base-tests/pom.xml
sql/sql-hibernate-test-util/pom.xml
sql/sql-memory-test-util/pom.xml
testng/testng-jvm-test/pom.xml
testng/testng-test-util/pom.xml

- Replace missing flight recorder dependency with 8.3.1
- Remove unused Maven repository
- Update minimum JDK version to 1.8 for JVM module
- Fix code that broke because of the updates
- Update CI pipeline to use updated versions
Resolves #220

fix: Cannot build quick perf from sources
